Bump jackson2.version from 2.16.1 to 2.17.0
Bumps `jackson2.version` from 2.16.1 to 2.17.0.

Updates `com.fasterxml.jackson.core:jackson-core` from 2.16.1 to 2.17.0
- [Commits](https://github.com/FasterXML/jackson-core/compare/jackson-core-2.16.1...jackson-core-2.17.0)

Updates `com.fasterxml.jackson.core:jackson-databind` from 2.16.1 to 2.17.0
- [Commits](https://github.com/FasterXML/jackson/commits)

Updates `com.fasterxml.jackson.datatype:jackson-datatype-json-org` from 2.16.1 to 2.17.0
- [Commits](https://github.com/FasterXML/jackson-datatypes-misc/compare/jackson-datatypes-misc-parent-2.16.1...jackson-datatypes-misc-parent-2.17.0)

Updates `com.fasterxml.jackson.core:jackson-annotations` from 2.16.1 to 2.17.0
- [Commits](https://github.com/FasterXML/jackson/commits)

Updates `com.fasterxml.jackson.module:jackson-module-scala_2.12` from 2.16.1 to 2.17.0
- [Changelog](https://github.com/FasterXML/jackson-module-scala/blob/2.17/release.sbt)
- [Commits](https://github.com/FasterXML/jackson-module-scala/compare/v2.16.1...v2.17.0)

Updates `com.fasterxml.jackson.module:jackson-module-paranamer` from 2.16.1 to 2.17.0
- [Commits](https://github.com/FasterXML/jackson-modules-base/compare/jackson-modules-base-2.16.1...jackson-modules-base-2.17.0)

---
updated-dependencies:
- dependency-name: com.fasterxml.jackson.core:jackson-core
  dependency-type: direct:production
  update-type: version-update:semver-minor
- dependency-name: com.fasterxml.jackson.core:jackson-databind
  dependency-type: direct:production
  update-type: version-update:semver-minor
- dependency-name: com.fasterxml.jackson.datatype:jackson-datatype-json-org
  dependency-type: direct:production
  update-type: version-update:semver-minor
- dependency-name: com.fasterxml.jackson.core:jackson-annotations
  dependency-type: direct:production
  update-type: version-update:semver-minor
- dependency-name: com.fasterxml.jackson.module:jackson-module-scala_2.12
  dependency-type: direct:production
  update-type: version-update:semver-minor
- dependency-name: com.fasterxml.jackson.module:jackson-module-paranamer
  dependency-type: direct:production
  update-type: version-update:semver-minor
...

Add <dependencyManagement> for `byte-buddy` to solve a dependency
convergence error:

```
Error:  Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.4.1:enforce (enforce-dependency-convergence) on project janusgraph-all:
Error:  Rule 1: org.apache.maven.enforcer.rules.dependency.DependencyConvergence failed with message:
Error:  Failed while enforcing releasability.
Error:
Error:  Dependency convergence error for net.bytebuddy:byte-buddy:jar:1.12.19 paths to dependency are:
Error:  +-org.janusgraph:janusgraph-all:jar:1.1.0-SNAPSHOT
Error:    +-org.janusgraph:janusgraph-server:jar:1.1.0-SNAPSHOT:compile
Error:      +-com.jcabi:jcabi-manifests:jar:2.1.0:compile
Error:        +-com.jcabi:jcabi-log:jar:0.22.0:compile
Error:          +-org.mockito:mockito-core:jar:4.11.0:compile
Error:            +-net.bytebuddy:byte-buddy:jar:1.12.19:compile
Error:  and
Error:  +-org.janusgraph:janusgraph-all:jar:1.1.0-SNAPSHOT
Error:    +-com.fasterxml.jackson.core:jackson-databind:jar:2.17.0:compile
Error:      +-net.bytebuddy:byte-buddy:jar:1.14.9:compile
Error:  -> [Help 1]
```

Signed-off-by: dependabot[bot] <support@github.com>
(cherry picked from commit 87a0101a2f313959135c339a04fa36fb7638bdfc)