Fix titan-all dependency problems
This commit makes two changes in titan-all's dependency tree:

1. titan-all now depends on hbase-client 0.98.2-hadoop2.  Before, it
   didn't depend on an hbase/hbase-client version, relying on the user
   to set one or exclude the titan-hbase module in their own pom.
   titan-all now sets a default version to avoid
   NoClassDefFoundErrors.  Downstream poms can override or exclude it
   as desired.

2. titan-all now explicitly declares dependencies on the Jackson 1.x
   and 2.y artifacts that it indirectly uses.  titan-all doesn't
   directly use Jackson, but its transitive deps do.  Furthermore,
   those transitive deps brought in a combination of 1.8 and 1.9 jars,
   and this led to NoClassDefFoundErrors at runtime.  Now titan-all
   sets all the affected artifacts to the same version declared in
   dependencyManagement.

   Importing dependencyManagement might be the cleaner approach:

   http://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Importing_Dependencies

   However, I'm wary of imposing additional requirements on downstream
   poms that want to use titan-all.  Also, I don't know whether
   dependencyManagement imports work on non-Maven tools that parse
   poms, such as gradle or sbt.  The approach in this commit is
   stupider than dependencyManagement imports but also simpler and
   should work regardless of the tool manipulating the downstream pom.