Introduce JanusGraphManagerUtility#getInstance
This allows us to avoid `NoClassDefFoundError` errors when users do not
require the optional gremlin-server dependency.

Issues: #565
Signed-off-by: David Pitera <dpitera@us.ibm.com>