Fix snakeyaml NoSuchMethodError in remote console (#3764)
Fix snakeyaml NoSuchMethodError in the remote console

When connecting to a remote gremlin server from the gremlin
console, a NoSuchMethodError is thrown. This commit fixes
this bug and adds an integration test to verify correctness.

Fixes #3763

Signed-off-by: Boxuan Li <liboxuan@connect.hku.hk>
(cherry picked from commit 7c9c30c766e04bb8e283f4880c853cce64123132)